### ISSUE TITLE
Add last page to showcase

### ISSUE THREAD

**Issue by ineiti** [c4dt/Garfield#18]
I propose to add the text from the last page to the showcase, perhaps as `Detailed information`.

Why: today I wanted to read this text, but I had to go through the whole demonstrator to access it.

Alternative: make it so that one can click directly on the last page...

**Comment by cgrigis** [comment]
What part of the text are you referring to? Globally it is a comparison of various projects, so IMHO would belong more into a Factory presentation than a particular showcase project description.
Perhaps I can add the part regarding the Byzantine and SMC Garfield implementation in the Garfield showcase "Presentation" page?

**Comment by ineiti** [comment]
One reason to put it in the `Detailed information` is that this is thought to give a more generic overview. So perhaps the `Detailed information` tag is misleading...

E.g., the AT2 and Omniledger have a short overview of blockchains in general. Spindle has a short introduction to ML. So having another short overview of comparison of projects in ML for the garfield showcase entry would fit.

**Comment by cgrigis** [comment]
Garfield has a short overview of distributed ML and Byzantine faults.

But here we are talking about a comparison between different projects from the showcase, which seems strange to me to put in _one_ of the projects.

**Comment by ineiti** [comment]
> which seems strange to me to put in _one_ of the projects.

Yes, that's the downside of a tree-structured information system. I think a tag-based or more mind-like information system would be much better. Perhaps I should change my side-project :)

Anyway - let's put it somewhere it can be easily found, as I think it's very interesting information. So if you prefer to put it at the beginning of the demo, let's put it there. For me the Garfield entry in the showcase would also make sense and make it easier for me to find it. But as you say, it's not clear if it should be in the Garfield or Spindle entry.
